### ISSUE TITLE
Reflected contract schema invalid for all optional arguments

### ISSUE THREAD

**Issue by griffithsrac** [hyperledger/fabric-contract-api-go#154]
Currently you cannot create a contract with a method in which all arguments are optional. Instead you get an error when creating the chaincode as the reflected metadata doesn't produce a valid JSON schema. This is because there are some components with an empty `required` field, whereas draft-04 of the JSON schema specifies all required fields must contain at least 1 value (so if all fields are optional the required field should be omitted entirely instead),

Example:
```golang
package main

import (
	"github.com/hyperledger/fabric-contract-api-go/v2/contractapi"
)

// SimpleContract with biz logic
type SimpleContract struct {
	contractapi.Contract
}

type Args struct {
	OptionalOne string `json:"optional_one" metadata:",optional"`
	OptionalTwo string `json:"optional_two" metadata:",optional"`
}

// HelloWorld - returns a string
func (sc *SimpleContract) HelloWorld(ctx contractapi.TransactionContextInterface, args *Args) string {
	return "Hello World"
}

func main() {
	simpleContract := new(SimpleContract)

	cc, err := contractapi.NewChaincode(simpleContract)

	if err != nil {
		panic(err.Error())
	}

	if err := cc.Start(); err != nil {
		panic(err.Error())
	}
}
```

Will give:
```
panic: cannot use metadata. Metadata did not match schema:
1. components.schemas.Args.required: Array must have at least 1 items
```

I think the issue here is that:
- the contract schema is generated through reflection and includes an empty array (`"required:" []`) i.e. all fields are optional.
- the version of JSON schema used via `packr` (see `metadata/schema/schema.json`) has `"objecttype.properties.required.$ref": "http://json-schema.org/draft-04/schema#/definitions/stringArray"`
- and in draft-04 stringArray's had to have a minimum length of 1.

I think this can probably be fixed in a number of ways...
1. We could add `omitempty` to the JSON tag of the `required` field in `metadata.ObjectMetadata` so that if there are no required fields then the `required` field isn't included (to match draft-04 of the spec). I think this should just be a 1 word fix and mean that the generated contract schema is correct as per draft-04 schemas.
2. Or we change which draft is used to a later version (which allows for empty `required` lists), i.e. explicitly saying all fields are optional. Not sure what other changes have been made since draft-04 though, so I can't say if this would have other effects or not.

**Comment by bestbeforetoday** [comment]
Thank you for raising this issue. If a schema with the `required` field omitted is valid in all later versions of the JSON schema specification, that seems like the most pragmatic solution. Perhaps it is worth doing regardless of schema specification version for better compatibility.

I am open to updating the schema specification version too, although support seems to be lacking for the latest schema specifications in tools like VS Code.

**Comment by griffithsrac** [comment]
Thanks for this! I meant to do a PR but got sidetracked with other things (sorry) and it wouldn't have been as complete as yours anyway!

**Comment by bestbeforetoday** [comment]
You’re welcome!
