### ISSUE TITLE
Update dependence "github.com/cucumber/godog" to v0.8.1

### ISSUE THREAD

**Issue by Alex-duzhichao** [hyperledger/fabric-contract-api-go#55]
As [discussion](https://github.com/cucumber/godog/issues/212#issuecomment-685416938) in [issue](https://github.com/cucumber/godog/issues/212) says, `godog@0.8.0` had been changed after its first commit. So that different goproxys maybe cache different `godog@0.8.0`, and go compiler maybe complain `verifying github.com/cucumber/godog@v0.8.0/go.mod: checksum mismatch`.

Update "github.com/cucumber/godog" to v0.8.1 should fix this problem.

**Comment by jt-nti** [comment]
Thanks for the issue and PR. The version of godog was updated to v0.12.5 while getting the build process working again, so hopefully this issue is resolved.
